before:
  hooks:
    - 'go mod tidy'

builds:
  -
    env:
      - 'CGO_ENABLED=0'
      - 'GO111MODULE=on'
      - 'GOPROXY=https://proxy.golang.org,direct'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-a'
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X={{ .ModulePath }}/internal/version.Name=go-integcov'
      - '-X={{ .ModulePath }}/internal/version.Version={{ .Version }}'
      - '-X={{ .ModulePath }}/internal/version.Commit={{ .Commit }}'
      - '-extldflags=-static'
    goos:
      - 'darwin'
      - 'linux'
      - 'windows'
    goarch:
      - 'amd64'
      - 'arm64'
    binary: 'go-integcov'

dockers:
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'amd64'
    image_templates:
      - 'ghcr.io/yolocs/go-integcov:{{ .Major }}-amd64'
      - 'ghcr.io/yolocs/go-integcov:{{ .Version }}-amd64'
      - 'ghcr.io/yolocs/go-integcov:latest-amd64'
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=go-integcov is a POC tool for collecting Go integration test coverage from remote.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=go-integcov'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=go-integcov'
      - '--label=org.opencontainers.image.version={{ .Version }}'
  -
    use: 'buildx'
    goos: 'linux'
    goarch: 'arm64'
    image_templates:
      - 'ghcr.io/yolocs/go-integcov:{{ .Major }}-arm64'
      - 'ghcr.io/yolocs/go-integcov:{{ .Version }}-arm64'
      - 'ghcr.io/yolocs/go-integcov:latest-arm64'
    build_flag_templates:
      - '--platform=linux/arm64'
      - '--pull'
      - '--label=org.opencontainers.image.created={{ .CommitTimestamp }}'
      - '--label=org.opencontainers.image.description=go-integcov is a POC tool for collecting Go integration test coverage from remote.'
      - '--label=org.opencontainers.image.licenses=Apache-2.0'
      - '--label=org.opencontainers.image.name=go-integcov'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.source={{ .GitURL }}'
      - '--label=org.opencontainers.image.title=go-integcov'
      - '--label=org.opencontainers.image.version={{ .Version }}'

docker_manifests:
  -
    name_template: 'ghcr.io/yolocs/go-integcov:{{ .Major }}'
    image_templates:
      - 'ghcr.io/yolocs/go-integcov:{{ .Major }}-amd64'
      - 'ghcr.io/yolocs/go-integcov:{{ .Major }}-arm64'
  -
    name_template: 'ghcr.io/yolocs/go-integcov:{{ .Version }}'
    image_templates:
      - 'ghcr.io/yolocs/go-integcov:{{ .Version }}-amd64'
      - 'ghcr.io/yolocs/go-integcov:{{ .Version }}-arm64'
  -
    name_template: 'ghcr.io/yolocs/go-integcov:latest'
    image_templates:
      - 'ghcr.io/yolocs/go-integcov:latest-amd64'
      - 'ghcr.io/yolocs/go-integcov:latest-arm64'

archives:
  - format: 'tar.gz'
    name_template: 'go-integcov_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'

checksum:
  name_template: 'go-integcov_{{ .Version }}_SHA512SUMS'
  algorithm: 'sha512'

changelog:
  use: 'github'

release:
  draft: false
  mode: 'replace'
